Repository oracle/truffleruby, pull requests merged in 2019-11, with the labels that each got.

#1781 Extract GRAAL_DIR to point to the path were graal will be cloned
  tool/jt.rb
Labels: in-ci, oca-signed

#1782 Some options tested in specs need --experimental-options
  spec/truffle/launcher_spec.rb
  spec/truffle/options/cexts_spec.rb
  spec/truffle/options/defaults_spec.rb
  spec/truffle/options/embedded_spec.rb
  spec/truffle/options/parsing_spec.rb
  spec/truffle/options/platform_native_spec.rb
  spec/truffle/pre_initialization_spec.rb
Labels: in-ci, oca-signed

#1793 Add Rafael França and Alan Wu to authors
  README.md
Labels: in-ci, oca-signed

#1799 Avoid warning when loading BigDecimal from YAML
  lib/truffle/bigdecimal.rb
Labels: in-ci, oca-signed

#1804 Process::Status#==: compare raw process status
  spec/ruby/core/process/status/equal_value_spec.rb
  spec/tags/core/process/status/equal_value_tags.txt
Labels: in-ci, oca-signed

#1807 Factor out a common exception pattern
  src/main/java/org/truffleruby/language/backtrace/BacktraceFormatter.java
  src/main/java/org/truffleruby/language/loader/RequireNode.java
  src/main/java/org/truffleruby/language/methods/TranslateExceptionNode.java
Labels: in-ci, oca-signed

#1813 The '--cpusampler.SampleInternal=true' option requires '--experimental-options'.
  tool/jt.rb
Labels: oca-signed

#1829 Run jt lint in TravisCI for Pull Requests
  ci.jsonnet
  test/truffle/ecosystem/blog-shared.sh
  tool/jt.rb
Labels: in-ci, oca-signed, oracle-emp
