Repository oracle/truffleruby, pull requests merged in 2020-10, with the labels that each got.

#2110 Support refinemnets for String#to_s
  CHANGELOG.md
  spec/tags/core/module/refine_tags.txt
  src/main/java/org/truffleruby/core/cast/ToSNode.java
Labels: in-ci, oca-signed

#2112 Module#using raises error in method scope
  CHANGELOG.md
  spec/tags/core/module/using_tags.txt
  src/main/java/org/truffleruby/core/module/ModuleNodes.java
Labels: in-ci, oca-signed

#2114 Detect recursion
  lib/truffle/truffle/cext.rb
  spec/truffle/thread/detect_recursion_spec.rb
  src/main/java/org/truffleruby/core/CoreLibrary.java
  src/main/ruby/truffleruby/core/array.rb
  src/main/ruby/truffleruby/core/comparable.rb
  src/main/ruby/truffleruby/core/enumerator.rb
  src/main/ruby/truffleruby/core/file.rb
  src/main/ruby/truffleruby/core/hash.rb
  src/main/ruby/truffleruby/core/kernel.rb
  src/main/ruby/truffleruby/core/string.rb
  src/main/ruby/truffleruby/core/struct.rb
  src/main/ruby/truffleruby/core/thread.rb
  src/main/ruby/truffleruby/core/truffle/interop.rb
  src/main/ruby/truffleruby/core/truffle/io_operations.rb
  src/main/ruby/truffleruby/core/truffle/thread_operations.rb
  test/truffle/compiler/pe/pe.rb
  test/truffle/compiler/pe/truffle/thread_pe.rb
Labels: in-ci, oca-signed

#2120 Support refinements for Kernel#respond_to?
  CHANGELOG.md
  lib/truffle/truffle/cext.rb
  spec/tags/core/module/refine_tags.txt
  src/main/c/cext/range.c
  src/main/java/org/truffleruby/core/kernel/KernelNodes.java
  test/mri/excludes/TestRefinement.rb
Labels: in-ci, oca-signed

#2129 Update to Joni 2.1.40 and JCodings 1.0.55
  3rd_party_licenses.txt
  CHANGELOG.md
  mx.truffleruby/suite.py
Labels: in-ci

#2131 Implement String#undump
  CHANGELOG.md
  spec/tags/core/string/undump_tags.txt
  src/main/java/org/truffleruby/core/array/ArrayUtils.java
  src/main/java/org/truffleruby/core/string/EncodingUtils.java
  src/main/java/org/truffleruby/core/string/StringNodes.java
  src/main/java/org/truffleruby/core/string/StringSupport.java
Labels: compatibility, in-ci, oca-signed
