Repository oracle/truffleruby, pull requests merged in 2021-09, with the labels that each got.

#2440 Add notes on passing --env to mx for the Eclipse setup and using MX_BUILD_EXPLODED/LINKY_LAYOUT
  doc/contributor/using-eclipse.md
Labels: in-ci

#2447 Use TRegex ASCII encoding if the regexp encoding is US-ASCII and the match string is CR_7BIT.
  CHANGELOG.md
  common.json
  mx.truffleruby/suite.py
  src/main/java/org/truffleruby/core/regexp/TRegexCache.java
Labels: performance, oca-signed, in-ci, shopify

#2449 jt graph command
  tool/jt.rb
Labels: oca-signed, in-ci, shopify, tooling
