Repository oracle/truffleruby, pull requests merged in 2021-06, with the labels that each got.

#2361 Improve time_strftime's performance
  CHANGELOG.md
  spec/ruby/library/datetime/strftime_spec.rb
  spec/ruby/shared/time/strftime_for_time.rb
  src/main/java/org/truffleruby/core/rope/LazyIntRope.java
  src/main/java/org/truffleruby/core/rope/LeafRope.java
  src/main/java/org/truffleruby/core/rope/RopeBuilder.java
  src/main/java/org/truffleruby/core/rope/RopeConstants.java
  src/main/java/org/truffleruby/core/rope/RopeNodes.java
  src/main/java/org/truffleruby/core/rope/TruffleRopesNodes.java
  src/main/java/org/truffleruby/core/time/RubyDateFormatter.java
  src/main/java/org/truffleruby/core/time/TimeNodes.java
Labels: in-ci, oca-signed, shopify

#2370 Fix formatting of microseconds in `Time#strftime`'s fast-path.
  src/main/java/org/truffleruby/core/time/RubyDateFormatter.java
Labels: in-ci, oca-signed

#2372 Add IO#set_encoding_by_bom method
  spec/ruby/core/io/set_encoding_by_bom_spec.rb
  spec/tags/core/io/set_encoding_by_bom_tags.txt
  src/main/ruby/truffleruby/core/io.rb
Labels: compatibility, in-ci, oca-signed, shopify

#2373 Support sourcing the Spin environment file from a Bash script
  .spin/bin/env
Labels: in-ci, oca-signed

#2377 Add spec for use of :base in Dir#glob and tag it
  spec/ruby/core/dir/glob_spec.rb
  spec/tags/core/dir/glob_tags.txt
Labels: in-ci, oca-signed, shopify

#2379 Add fast-path for `rb_enc_from_index`.
  src/main/java/org/truffleruby/core/encoding/EncodingNodes.java
Labels: in-ci, oca-signed, shopify

#2380 Replace boundary on `StringByteIndexPrimitiveNode` with faster specializations for boundary checks and single-byte-optimizable strings.
  src/main/java/org/truffleruby/core/cast/ToRopeNode.java
  src/main/java/org/truffleruby/core/string/StringNodes.java
Labels: in-ci, oca-signed, shopify

#2384 Add fast paths for various `MatchData` methods.
  src/main/java/org/truffleruby/core/regexp/MatchDataNodes.java
  src/main/ruby/truffleruby/core/regexp.rb
Labels: in-ci, oca-signed, shopify
