Repository oracle/truffleruby, pull requests merged in 2021-07, with the labels that each got.

#2393 Clarify needed specializations in StringCharacterIndexNode
  src/main/java/org/truffleruby/core/string/StringNodes.java
  src/main/ruby/truffleruby/core/string.rb
Labels: in-ci, oca-signed, shopify

#2368 Option to add chaos to data representations to stress specialization code paths
  spec/truffle/array/append_spec.rb
  spec/truffle/array/element_set_spec.rb
  spec/truffle/array/steal_array_storage.rb
  spec/truffle/integer/and_spec.rb
  spec/truffle/integer/left_shift_spec.rb
  spec/truffle/integer/right_shift_spec.rb
  spec/truffle/interop/java_instanceof_spec.rb
  spec/truffle/truffleruby/concurrent_map_spec.rb
  src/main/java/org/truffleruby/core/format/format/FormatCharacterNode.java
  src/main/java/org/truffleruby/core/numeric/IntegerNodes.java
  src/main/java/org/truffleruby/debug/ChaosNode.java
  src/main/java/org/truffleruby/debug/TruffleDebugNodes.java
  src/main/java/org/truffleruby/options/LanguageOptions.java
  src/main/java/org/truffleruby/parser/Translator.java
  src/options.yml
  src/shared/java/org/truffleruby/shared/options/OptionsCatalog.java
Labels: compatibility, in-ci, oca-signed, shopify

#2394 Make Process.clock_gettime(Process::CLOCK_MONOTONIC) simpler
  src/main/java/org/truffleruby/core/ProcessNodes.java
  src/main/ruby/truffleruby/core/process.rb
Labels: in-ci, oca-signed, performance, shopify
