Repository oracle/truffleruby, pull requests merged in 2021-08, with the labels that each got.

#2413 Outline icon in white for dark backgrounds
  README.md
  logo/ai/truffleruby_logos_outlined.ai
  logo/png/truffleruby_logo_horizontal_medium_outlined.png
Labels: in-ci, oca-signed

#2409 Create ~/.rubies in Spin so that we can always use chruby easily
  .spin/bin/bootstrap
Labels: in-ci, oca-signed, shopify

#2411 Add missing changelog entries.
  CHANGELOG.md
Labels: in-ci, oca-signed, shopify

#2153 Integrate foreign objects better with Ruby objects
  CHANGELOG.md
  doc/contributor/interop_implicit_api.md
  spec/truffle/interop/fixtures/classes.rb
  spec/truffle/interop/foreign_array_spec.rb
  spec/truffle/interop/foreign_inspect_to_s_spec.rb
  spec/truffle/interop/polyglot/foreign_array_spec.rb
  spec/truffle/interop/polyglot/inner_context_spec.rb
  spec/truffle/interop/respond_to_spec.rb
  spec/truffle/interop/special_forms_spec.rb
  src/main/.checkstyle_checks.xml
  src/main/java/org/truffleruby/core/CoreLibrary.java
  src/main/java/org/truffleruby/core/basicobject/BasicObjectNodes.java
  src/main/java/org/truffleruby/core/kernel/KernelNodes.java
  src/main/java/org/truffleruby/core/klass/ClassNodes.java
  src/main/java/org/truffleruby/interop/InteropNodes.java
  src/main/java/org/truffleruby/interop/OutgoingForeignCallNode.java
  src/main/java/org/truffleruby/interop/ToJavaStringNode.java
  src/main/java/org/truffleruby/language/ImmutableRubyObject.java
  src/main/java/org/truffleruby/language/RubyDynamicObject.java
  src/main/java/org/truffleruby/language/dispatch/DispatchNode.java
  src/main/java/org/truffleruby/language/methods/CallForeignMethodNode.java
  src/main/java/org/truffleruby/language/methods/LookupMethodNode.java
  src/main/java/org/truffleruby/language/objects/ForeignClassNode.java
  src/main/java/org/truffleruby/language/objects/LogicalClassNode.java
  src/main/java/org/truffleruby/language/objects/MetaClassNode.java
  src/main/ruby/truffleruby/core/truffle/interop.rb
  src/main/ruby/truffleruby/core/truffle/interop_operations.rb
  src/main/ruby/truffleruby/core/truffle/polyglot.rb
  test/truffle/cexts/backtraces/expected.txt
Labels: oca-signed

#2428 Rewrite Struct comment so it isn't user-hostile
  src/main/ruby/truffleruby/core/struct.rb
Labels: oca-signed, in-ci, shopify

#2432 Fix Float#<=> for immutable objects
  CHANGELOG.md
  spec/ruby/core/float/comparison_spec.rb
  src/main/java/org/truffleruby/core/numeric/FloatNodes.java
Labels: oca-signed, in-ci, shopify

#2430 Add more comprehensive regexp instrumentation
  src/main/java/org/truffleruby/core/hash/HashOperations.java
  src/main/java/org/truffleruby/core/regexp/InterpolatedRegexpNode.java
  src/main/java/org/truffleruby/core/regexp/RegexpCacheKey.java
  src/main/java/org/truffleruby/core/regexp/RegexpNodes.java
  src/main/java/org/truffleruby/core/regexp/TruffleRegexpNodes.java
  src/main/java/org/truffleruby/options/Options.java
  src/main/java/org/truffleruby/parser/BodyTranslator.java
  src/main/ruby/truffleruby/core/truffle/regexp_operations.rb
  src/options.yml
  src/shared/java/org/truffleruby/shared/options/OptionsCatalog.java
Labels: oca-signed, in-ci, shopify
