Repository oracle/truffleruby, pull requests merged in 2021-04, with the labels that each got.

#2306 Do not rely on exceptions in Struct#dig
  spec/ruby/core/struct/dig_spec.rb
  src/main/ruby/truffleruby/core/struct.rb
  src/main/ruby/truffleruby/core/truffle/diggable.rb
Labels: in-ci, oca-signed, shopify

#2311 Debugging documentation for contributors
  doc/contributor/debugging.md
  src/main/java/org/truffleruby/RubyLanguage.java
Labels: documentation, in-ci, oca-signed, shopify

#2308 Support precision when formatting string
  spec/ruby/core/kernel/format_spec.rb
  spec/tags/core/kernel/format_tags.txt
  src/main/java/org/truffleruby/core/format/TruncateStringNode.java
  src/main/java/org/truffleruby/core/format/pack/SimplePackTreeBuilder.java
  src/main/java/org/truffleruby/core/format/printf/PrintfSimpleTreeBuilder.java
  src/main/java/org/truffleruby/core/format/read/array/ReadStringNode.java
Labels: in-ci, oca-signed

#2327 Print some basic regex stats if the instrumentation is enabled
  src/main/ruby/truffleruby/core/truffle/regexp_operations.rb
Labels: in-ci, oca-signed, shopify

#2320 Make rpartition compatible with Ruby 2.7
  CHANGELOG.md
  spec/ruby/core/string/rpartition_spec.rb
  src/main/ruby/truffleruby/core/string.rb
  test/mri/excludes/TestString.rb
Labels: in-ci, oca-signed

#2329 Fix Kernel#inspect fails if an object doesn't have #class method
  spec/ruby/core/kernel/inspect_spec.rb
  src/main/ruby/truffleruby/core/kernel.rb
Labels: in-ci, oca-signed

#2328 Make String#inspect readable with Unicode-coded strings
  spec/ruby/core/string/inspect_spec.rb
  src/main/ruby/truffleruby/core/string.rb
Labels: in-ci, oca-signed
