Repository oracle/truffleruby, pull requests merged in 2021-03, with the labels that each got.

#2279 Add more specs for c-ext methods arity
  spec/ruby/optional/capi/ext/module_spec.c
  spec/ruby/optional/capi/module_spec.rb
  spec/tags/optional/capi/module_tags.txt
Labels: in-ci, oca-signed, shopify

#2275 Fix incorrect arity for C-extension methods
  lib/truffle/truffle/cext_ruby.rb
  src/main/java/org/truffleruby/core/proc/ProcNodes.java
  src/main/java/org/truffleruby/core/proc/RubyProc.java
  src/main/java/org/truffleruby/language/methods/SharedMethodInfo.java
Labels: in-ci, oca-signed, shopify

#2287 Improve specification and compatibility of implementation of Signal.trap
  CHANGELOG.md
  spec/ruby/core/kernel/trap_spec.rb
  spec/ruby/core/signal/trap_spec.rb
  spec/tags/core/signal/trap_tags.txt
  src/main/java/org/truffleruby/core/VMPrimitiveNodes.java
  src/main/ruby/truffleruby/core/signal.rb
Labels: compatibility, in-ci, oca-signed, shopify

#2293 Fix use of vm_watch_signal as it now passes signo
  src/main/ruby/truffleruby/core/main.rb
Labels: bug, in-ci, oca-signed, shopify

#2297 Spin configuration
  .spin/bin/bootstrap
  .spin/bin/env
Labels: in-ci, oca-signed, shopify

#2301 Make #dig iterative
  src/main/java/org/truffleruby/core/CoreLibrary.java
  src/main/java/org/truffleruby/core/VMPrimitiveNodes.java
  src/main/ruby/truffleruby/core/array.rb
  src/main/ruby/truffleruby/core/hash.rb
  src/main/ruby/truffleruby/core/struct.rb
  src/main/ruby/truffleruby/core/truffle/diggable.rb
Labels: in-ci, oca-signed, shopify

#2223 Added linux-musl support
  mx.truffleruby/suite.py
  src/main/c/cext/extconf.rb
  src/main/c/cext/printf.c
  src/main/c/cext/printf_musl.c
Labels: in-ci, oca-signed
