Repository oracle/truffleruby, pull requests merged in 2021-02, with the labels that each got.

#2244 Implement rb_scan_args_kw
  lib/cext/include/truffleruby/truffleruby.h
  spec/tags/optional/capi/util_tags.txt
Labels: compatibility, in-ci, oca-signed, shopify

#2249 Fix String#scrub!
  spec/ruby/core/string/scrub_spec.rb
  src/main/ruby/truffleruby/core/string.rb
Labels: in-ci, oca-signed, shopify

#2255 Fix OpenSSL::Engine build on Debian
  src/main/c/openssl/ossl_engine.c
Labels: in-ci, oca-signed

#2270 Add specs for arity in C-ext methods
  spec/ruby/optional/capi/module_spec.rb
  spec/tags/optional/capi/module_tags.txt
Labels: in-ci, oca-signed, shopify
