Repository oracle/truffleruby, pull requests merged in 2022-01, with the labels that each got.

#2557 Update MacPorts heuristic to find OpenSSL 1.1, since 3 is not compatible
  lib/truffle/truffle/openssl-prefix.rb
Labels: oca-signed, in-ci

#2571 Unwrap ropes in StringEqualNode to avoid need for StringAreComparableNode
  src/main/java/org/truffleruby/core/inlined/InlinedEqualNode.java
  src/main/java/org/truffleruby/core/string/StringNodes.java
Labels: oca-signed, in-ci

#2570 Override freeze-related behaviour in RubyRange for compatibility with Ruby 3.0
  spec/ruby/language/range_spec.rb
  spec/tags/language/range_tags.txt
  src/main/java/org/truffleruby/core/range/RangeNodes.java
  src/main/java/org/truffleruby/core/range/RubyIntRange.java
  src/main/java/org/truffleruby/core/range/RubyLongRange.java
  src/main/java/org/truffleruby/core/range/RubyObjectRange.java
  src/main/java/org/truffleruby/core/range/RubyRange.java
Labels: performance, oca-signed, in-ci

#2532 When writing to STDOUT redirected to a closed pipe, no broken pipe
  CHANGELOG.md
  spec/ruby/core/io/write_spec.rb
  spec/tags/core/io/write_tags.txt
  src/main/ruby/truffleruby/core/posix.rb
  test/mri/excludes/TestIO.rb
  test/mri/excludes/TestPipe.rb
  test/mri/excludes/TestPipe/WithConversion.rb
Labels: oca-signed, in-ci

#2576 Disabling FullUnroll is unhelpful for jt graph
  tool/jt.rb
Labels: oca-signed, in-ci

#2581 Truffle::Debug.foreign_identity_function
  src/main/java/org/truffleruby/debug/TruffleDebugNodes.java
Labels: oca-signed, in-ci, shopify

#2585 Fix typo in TruffleKernelNodes.java
  src/main/java/org/truffleruby/core/kernel/TruffleKernelNodes.java
Labels: oca-signed, in-ci, shopify

#2582 Add additional specs for #ruby2_keywords
  spec/ruby/core/module/ruby2_keywords_spec.rb
  spec/ruby/core/proc/ruby2_keywords_spec.rb
  spec/tags/core/module/ruby2_keywords_tags.txt
  spec/tags/core/proc/ruby2_keywords_tags.txt
Labels: oca-signed, in-ci, shopify
