Repository oracle/truffleruby, pull requests merged in 2022-02, with the labels that each got.

#2584 Mark keyword argument hashes in the parser
  src/main/java/org/truffleruby/Layouts.java
  src/main/java/org/truffleruby/core/binding/BindingNodes.java
  src/main/java/org/truffleruby/parser/TranslatorEnvironment.java
  src/main/java/org/truffleruby/parser/ast/HashParseNode.java
  src/main/java/org/truffleruby/parser/parser/ParserSupport.java
  src/main/java/org/truffleruby/parser/parser/RubyParser.java
  src/main/java/org/truffleruby/parser/parser/RubyParser.y
Labels: oca-signed, in-ci, shopify

#2539 jt graph --describe
  bin/jt
  ci.jsonnet
  src/main/java/org/truffleruby/platform/DarwinAMD64NativeConfiguration.java
  test/truffle/compiler/graphs.sh
  test/truffle/compiler/graphs/args-opt-set.rb
  test/truffle/compiler/graphs/args-opt-unset.rb
  test/truffle/compiler/graphs/args-req.rb
  test/truffle/compiler/graphs/args-rest.rb
  test/truffle/compiler/graphs/run.rb
  tool/jt.rb
Labels: oca-signed, in-ci, shopify

#2592 Stronger asserts on the calling convention
  src/main/java/org/truffleruby/core/array/ArrayHelpers.java
  src/main/java/org/truffleruby/core/array/ArrayUtils.java
  src/main/java/org/truffleruby/core/method/MethodNodes.java
  src/main/java/org/truffleruby/language/arguments/RubyArguments.java
  src/main/java/org/truffleruby/language/methods/CallInternalMethodNode.java
  src/main/java/org/truffleruby/language/threadlocal/SpecialVariableStorage.java
Labels: oca-signed, in-ci

#2594 Dont call IO#flush from within IO#close
  CHANGELOG.md
  CONTRIBUTING.md
  spec/ruby/core/io/close_spec.rb
  src/main/ruby/truffleruby/core/io.rb
Labels: oca-signed, compatibility, in-ci

#2587 Fix crash caused by mutating an array within the .each call block
  CHANGELOG.md
  spec/ruby/core/array/each_spec.rb
  src/main/java/org/truffleruby/core/array/ArrayEachIteratorNode.java
Labels: performance, oca-signed, compatibility, in-ci, shopify

#2598 Added Seafoam generated illustrations to .gitignore
  .gitignore
Labels: oca-signed, in-ci
