Repository oracle/truffleruby, pull requests merged in 2022-03, with the labels that each got.

#2624 Introduce an arguments descriptor that says keyword arguments are present
  spec/truffle/arguments_descriptor_spec.rb
  src/main/java/org/truffleruby/RubyContext.java
  src/main/java/org/truffleruby/cext/CExtNodes.java
  src/main/java/org/truffleruby/core/VMPrimitiveNodes.java
  src/main/java/org/truffleruby/core/basicobject/BasicObjectNodes.java
  src/main/java/org/truffleruby/core/binding/BindingNodes.java
  src/main/java/org/truffleruby/core/fiber/FiberManager.java
  src/main/java/org/truffleruby/core/fiber/FiberNodes.java
  src/main/java/org/truffleruby/core/kernel/AtExitManager.java
  src/main/java/org/truffleruby/core/kernel/KernelNodes.java
  src/main/java/org/truffleruby/core/method/MethodNodes.java
  src/main/java/org/truffleruby/core/method/RubyMethod.java
  src/main/java/org/truffleruby/core/module/ModuleNodes.java
  src/main/java/org/truffleruby/core/proc/ProcNodes.java
  src/main/java/org/truffleruby/core/proc/ProcOperations.java
  src/main/java/org/truffleruby/core/symbol/SymbolNodes.java
  src/main/java/org/truffleruby/core/thread/ThreadNodes.java
  src/main/java/org/truffleruby/debug/DebugHelpers.java
  src/main/java/org/truffleruby/extra/TruffleGraalNodes.java
  src/main/java/org/truffleruby/language/RubyInlineParsingRequestNode.java
  src/main/java/org/truffleruby/language/RubyParsingRequestNode.java
  src/main/java/org/truffleruby/language/arguments/ArgumentsDescriptor.java
  src/main/java/org/truffleruby/language/arguments/EmptyArgumentsDescriptor.java
  src/main/java/org/truffleruby/language/arguments/KeywordArgumentsDescriptor.java
  src/main/java/org/truffleruby/language/arguments/ReadUserKeywordsHashNode.java
  src/main/java/org/truffleruby/language/arguments/RubyArguments.java
  src/main/java/org/truffleruby/language/dispatch/DispatchNode.java
  src/main/java/org/truffleruby/language/dispatch/RubyCallNode.java
  src/main/java/org/truffleruby/language/dispatch/RubyCallNodeParameters.java
  src/main/java/org/truffleruby/language/loader/CodeLoader.java
  src/main/java/org/truffleruby/language/methods/CallInternalMethodNode.java
  src/main/java/org/truffleruby/language/objects/RunModuleDefinitionNode.java
  src/main/java/org/truffleruby/language/supercall/CallSuperMethodNode.java
  src/main/java/org/truffleruby/language/supercall/SuperCallNode.java
  src/main/java/org/truffleruby/language/yield/CallBlockNode.java
  src/main/java/org/truffleruby/language/yield/YieldExpressionNode.java
  src/main/java/org/truffleruby/parser/BodyTranslator.java
  src/main/java/org/truffleruby/parser/MethodTranslator.java
  src/main/ruby/truffleruby/core/thread.rb
Labels: compatibility, in-ci

#2628 Add Truffle::Graal.total_compilation_time
  src/main/java/org/truffleruby/extra/TruffleGraalNodes.java
  tool/jt.rb
Labels: in-ci

#2638 Fix MatchData#[] with index and length
  CHANGELOG.md
  spec/ruby/core/matchdata/element_reference_spec.rb
  src/main/java/org/truffleruby/core/regexp/MatchDataNodes.java
Labels: oca-signed, in-ci, shopify
