Repository oracle/truffleruby, pull requests merged in 2022-07, with the labels that each got.

#2684 Add dirty repo status to RUBY_DESCRIPTION, and add jt build --new-hash
  src/processor/java/org/truffleruby/processor/BuildInformationProcessor.java
  src/shared/java/org/truffleruby/shared/BuildInformation.java
  src/shared/java/org/truffleruby/shared/TruffleRuby.java
  tool/jt.rb
Labels: oca-signed, in-ci, shopify, OCA Verified

#2686 If a call target supplier is fulfilled, just use it
  src/main/java/org/truffleruby/builtins/CoreMethodNodeManager.java
  src/main/java/org/truffleruby/collections/CachedSupplier.java
  src/main/java/org/truffleruby/language/methods/CachedLazyCallTargetSupplier.java
  src/main/java/org/truffleruby/language/methods/InternalMethod.java
  src/main/java/org/truffleruby/language/methods/LiteralMethodDefinitionNode.java
  src/main/java/org/truffleruby/parser/MethodTranslator.java
Labels: performance, oca-signed, in-ci, shopify

#2694 Add support for Ruby 3.1's Hash shorthand/punning syntax
  CHANGELOG.md
  spec/tags/language/hash_tags.txt
  spec/truffleruby.mspec
  src/main/java/org/truffleruby/parser/parser/RubyParser.java
  src/main/java/org/truffleruby/parser/parser/RubyParser.y
  src/main/java/org/truffleruby/parser/parser/YyTables.java
  test/mri/excludes/OpenSSL/TestOCSP.rb
  test/mri/excludes/TestThread.rb
Labels: in-ci, shopify, OCA Verified

#2696 ci: add GitHub token permissions for workflow
  .github/workflows/ci.yml
Labels: in-ci, OCA Verified
