Repository oracle/truffleruby, pull requests merged in 2023-01, with the labels that each got.

#2832 Implement `Array#intersect?`.
  CHANGELOG.md
  spec/ruby/core/array/intersect_spec.rb
  spec/tags/core/array/intersect_tags.txt
  src/main/ruby/truffleruby/core/array.rb
Labels: compatibility, shopify, OCA Verified

#2785 Run cfg2asm on jt graph
  .gitignore
  tool/jt.rb
Labels: in-ci, OCA Verified

#2837 Faster empty ivar accesses
  src/main/java/org/truffleruby/core/kernel/KernelNodes.java
  src/main/java/org/truffleruby/core/support/TypeNodes.java
Labels: performance, in-ci, shopify, OCA Verified
