Repository oracle/truffleruby, pull requests merged in 2023-03, with the labels that each got.

#2897 Fix `Marshal.dump` error message for anonymous classes
  spec/ruby/core/marshal/dump_spec.rb
Labels: compatibility, in-ci, shopify, OCA Verified

#2905 added Integer.try_convert, Ruby 3.1 support
  CHANGELOG.md
  spec/ruby/core/array/try_convert_spec.rb
  spec/ruby/core/hash/try_convert_spec.rb
  spec/ruby/core/integer/try_convert_spec.rb
  spec/ruby/core/io/try_convert_spec.rb
  spec/ruby/core/regexp/try_convert_spec.rb
  spec/ruby/core/string/try_convert_spec.rb
  spec/tags/core/integer/try_convert_tags.txt
  src/main/ruby/truffleruby/core/integer.rb
  src/main/ruby/truffleruby/core/type.rb
Labels: in-ci, OCA Verified

#2908 rb_gc_force_recycle is now no-op, Ruby 3.1 support
  CHANGELOG.md
  lib/cext/ABI_check.txt
  src/main/c/cext/gc.c
Labels: in-ci, OCA Verified

#2927 fix: StringIO#write transcodes strings with a different encoding
  CHANGELOG.md
  lib/truffle/stringio.rb
  spec/ruby/core/io/shared/write.rb
  spec/ruby/core/io/syswrite_spec.rb
  spec/ruby/core/io/write_nonblock_spec.rb
  spec/ruby/core/io/write_spec.rb
  spec/ruby/library/stringio/shared/write.rb
  src/main/ruby/truffleruby/core/io.rb
  src/main/ruby/truffleruby/core/truffle/io_operations.rb
Labels: in-ci, shopify, OCA Verified
