Repository oracle/truffleruby, pull requests merged in 2023-06, with the labels that each got.

#3055 FFI: Allow type retrieval of attached functions and global variables
  lib/truffle/truffle/ffi_backend/function.rb
  lib/truffle/truffle/ffi_backend/type.rb
Labels: in-ci, OCA Verified

#3088 [Bug] Fix singleton class lookup bug when singleton class is replaced on the instance
  CHANGELOG.md
  spec/ruby/core/kernel/singleton_class_spec.rb
  src/main/java/org/truffleruby/core/VMPrimitiveNodes.java
  src/main/java/org/truffleruby/core/support/TypeNodes.java
  src/main/java/org/truffleruby/language/RubyGuards.java
  src/main/java/org/truffleruby/language/objects/MetaClassNode.java
  src/main/java/org/truffleruby/language/objects/SingletonClassNode.java
Labels: in-ci, shopify, OCA Verified

#3045 [Compatibility] Add timeout to Queue#pop
  CHANGELOG.md
  lib/truffle/thread.rb
  lib/truffle/timeout.rb
  spec/ruby/core/queue/deq_spec.rb
  spec/ruby/core/queue/pop_spec.rb
  spec/ruby/core/queue/shift_spec.rb
  spec/ruby/shared/queue/deque.rb
  spec/ruby/shared/types/rb_num2dbl_fails.rb
  spec/truffle/objspace/define_finalizer_spec.rb
  spec/truffle/objspace/undefine_finalizer_spec.rb
  spec/truffleruby.next-specs
  src/main/java/org/truffleruby/core/CoreLibrary.java
  src/main/java/org/truffleruby/core/queue/QueueNodes.java
  src/main/java/org/truffleruby/core/thread/ThreadManager.java
  src/main/ruby/truffleruby/core/channel.rb
  src/main/ruby/truffleruby/core/truffle/queue_operations.rb
  src/main/ruby/truffleruby/core/type.rb
Labels: in-ci, shopify, OCA Verified

#3114 tool/import-yarp.sh should only generate the needed template files
  tool/import-yarp.sh
Labels: in-ci, shopify, OCA Verified

#3046 [Compatibility] Add timeout argument to Thread::SizedQueue#pop
  CHANGELOG.md
  lib/truffle/thread.rb
  spec/ruby/core/sizedqueue/deq_spec.rb
  spec/ruby/core/sizedqueue/pop_spec.rb
  spec/ruby/core/sizedqueue/shift_spec.rb
  spec/ruby/shared/queue/deque.rb
  spec/truffleruby.next-specs
  src/main/.checkstyle_checks.xml
  src/main/java/org/truffleruby/collections/ConcurrentOperations.java
  src/main/java/org/truffleruby/core/mutex/ConditionVariableNodes.java
  src/main/java/org/truffleruby/core/queue/SizedQueue.java
  src/main/java/org/truffleruby/core/queue/SizedQueueNodes.java
  src/main/java/org/truffleruby/core/queue/UnsizedQueue.java
  src/main/java/org/truffleruby/core/thread/ThreadManager.java
  src/main/ruby/truffleruby/core/truffle/queue_operations.rb
Labels: in-ci, shopify, OCA Verified

#3126 Run MRI tests in GitHub Actions
  .github/workflows/ci.yml
  ci.jsonnet
Labels: OCA Verified

#3133 [Bugfix] Fix super method lookup for unbounded added methods
  CHANGELOG.md
  spec/ruby/core/module/define_method_spec.rb
  spec/ruby/language/super_spec.rb
  src/main/java/org/truffleruby/core/module/ModuleNodes.java
Labels: in-ci, shopify, OCA Verified

#3093 [Compatibility] Add `Module#refinements`
  .gitattributes
  CHANGELOG.md
  spec/tags/truffle/methods_tags.txt
  spec/truffleruby.next-specs
  src/main/java/org/truffleruby/core/module/ModuleNodes.java
  test/mri/excludes/TestRefinement.rb
  test/mri/tests/ruby/test_refinement.rb
Labels: in-ci, shopify, OCA Verified
