Repository oracle/truffleruby, pull requests merged in 2023-04, with the labels that each got.

#2961 Read to separator fixes
  CHANGELOG.md
  spec/ruby/core/io/gets_spec.rb
  src/main/java/org/truffleruby/core/string/StringNodes.java
  src/main/java/org/truffleruby/core/support/ByteArrayNodes.java
  src/main/ruby/truffleruby/core/io.rb
Labels: bug, shopify, OCA Verified

#2975 Fix type coercion protocol
  CHANGELOG.md
  spec/ruby/core/array/plus_spec.rb
  spec/ruby/core/kernel/method_spec.rb
  spec/ruby/core/math/cos_spec.rb
  spec/ruby/core/module/alias_method_spec.rb
  spec/ruby/core/module/const_defined_spec.rb
  spec/ruby/core/queue/initialize_spec.rb
  spec/ruby/core/string/append_spec.rb
  spec/ruby/core/string/concat_spec.rb
  spec/ruby/core/string/plus_spec.rb
  spec/ruby/core/string/shared/concat.rb
  spec/tags/core/module/const_defined_tags.txt
  spec/truffle/always_inlined_spec.rb
  src/main/java/org/truffleruby/core/cast/ToANode.java
  src/main/java/org/truffleruby/core/cast/ToAryNode.java
  src/main/java/org/truffleruby/core/cast/ToFNode.java
  src/main/java/org/truffleruby/core/cast/ToStrNode.java
  src/main/java/org/truffleruby/core/cast/ToStringOrSymbolNode.java
  src/main/java/org/truffleruby/core/cast/ToSymbolNode.java
  src/main/java/org/truffleruby/core/inlined/AlwaysInlinedMethodNode.java
Labels: shopify, OCA Verified

#2984 Update spin
  .spin/packages.yml
Labels: in-ci, shopify, tooling

#2976 Update arg to ruby-install in docs
  doc/user/ruby-managers.md
Labels: in-ci, OCA Verified

#2980 [3.2 compatibility] Make an empty hash shift return nil
  CHANGELOG.md
  spec/tags/core/hash/shift_tags.txt
  spec/truffleruby.mspec
  src/main/java/org/truffleruby/core/hash/HashNodes.java
  test/mri/excludes/TestHash.rb
  test/mri/excludes/TestHash/TestSubHash.rb
Labels: shopify, OCA Verified

#2985 Reverse Array#shuffle implementation to match output of CRuby
  CHANGELOG.md
  spec/ruby/core/array/shuffle_spec.rb
  src/main/ruby/truffleruby/core/array.rb
Labels: in-ci, shopify, OCA Verified

#2986 Move "IRB history fix" changelog entry to bug fixes
  CHANGELOG.md
Labels: in-ci, shopify, OCA Verified

#2994 [docs] Extended the workflow documentation with `jt ruby` builds for ruby version managers
  doc/contributor/workflow.md
Labels: in-ci, shopify, OCA Verified

#2992 Remove duplicated Dir#ensure_open call
  CONTRIBUTING.md
  src/main/ruby/truffleruby/core/truffle/dir_operations.rb
Labels: in-ci, shopify, OCA Verified

#2981 [3.2 compatibility] Fix array slice with arithmetic sequence for Ruby v3.2
  CHANGELOG.md
  spec/tags/core/array/element_reference_tags.txt
  spec/truffleruby.next-specs
  src/main/java/org/truffleruby/core/array/ArrayNodes.java
  src/main/ruby/truffleruby/core/array.rb
  test/mri/excludes/TestArray.rb
Labels: in-ci, shopify, OCA Verified

#2978 [3.2 compatibility] Return nil for beginless ranges where the end is not numeric
  CHANGELOG.md
  spec/ruby/core/range/size_spec.rb
  spec/tags/core/range/size_tags.txt
  spec/truffleruby.next-specs
  src/main/ruby/truffleruby/core/range.rb
Labels: in-ci, shopify, OCA Verified
