Repository oracle/truffleruby, pull requests merged in 2024-04, with the labels that each got.

#3519 JDK 21 is necessary for SpotBugs, etc
  .github/workflows/ci.yml
Labels: OCA Verified

#3529 Avoid excessive splitting of nodes caused by a unique proc being created per call when a method reference would suffice.
  src/main/ruby/truffleruby/core/splitter.rb
  src/main/ruby/truffleruby/core/string.rb
Labels: performance, in-ci, shopify, OCA Verified

#3537 Report polymorphism for `sprintf` nodes.
  src/annotations/java/org/truffleruby/annotations/Split.java
  src/main/java/org/truffleruby/cext/CExtNodes.java
  src/main/java/org/truffleruby/core/array/ArrayNodes.java
  src/main/java/org/truffleruby/core/kernel/KernelNodes.java
  src/main/java/org/truffleruby/language/dispatch/DispatchNode.java
  src/main/ruby/truffleruby/core/io.rb
  src/main/ruby/truffleruby/core/kernel.rb
  src/main/ruby/truffleruby/core/string.rb
Labels: performance, in-ci, shopify, OCA Verified

#3491 Implement no args Struct.new constructor in Ruby 3.3
  spec/truffleruby.next-specs
  src/main/ruby/truffleruby/core/struct.rb
Labels: in-ci, shopify, OCA Verified
