Repository oracle/truffleruby, pull requests merged in 2024-01, with the labels that each got.

#3364 Properly handle argument Socket::INADDR_ANY in Socket.sockaddr_in.
  CHANGELOG.md
  lib/truffle/socket/truffle/foreign.rb
  spec/ruby/library/socket/shared/pack_sockaddr.rb
  spec/ruby/library/socket/socket/pack_sockaddr_in_spec.rb
  spec/tags/library/socket/socket/pack_sockaddr_in_tags.txt
Labels: in-ci, OCA Verified

#3341 Add Data.define
  CHANGELOG.md
  lib/mri/pp.rb
  lib/truffle/socket/ifaddr.rb
  lib/truffle/truffle/cext.rb
  spec/ruby/core/data/initialize_spec.rb
  spec/ruby/core/data/with_spec.rb
  spec/tags/core/data/define_tags.txt
  spec/tags/core/data/initialize_tags.txt
  src/main/java/org/truffleruby/cext/CExtNodes.java
  src/main/java/org/truffleruby/core/CoreLibrary.java
  src/main/ruby/truffleruby/core/data.rb
  src/main/ruby/truffleruby/core/struct.rb
  src/main/ruby/truffleruby/core/type.rb
  test/mri/excludes/TestData.rb
Labels: OCA Verified

#3402 Add `Integer#ceilvdiv`
  CHANGELOG.md
  spec/ruby/core/integer/div_spec.rb
  spec/tags/core/integer/ceildiv_tags.txt
  src/main/java/org/truffleruby/core/numeric/IntegerNodes.java
  src/main/ruby/truffleruby/core/integer.rb
Labels: in-ci, OCA Verified

#3411 [Compatibility] Accept options argument to `Regexp.{new,compile}` of String; Warn for unknown types
  CHANGELOG.md
  spec/ruby/core/regexp/shared/new.rb
  spec/tags/core/regexp/compile_tags.txt
  spec/tags/core/regexp/new_tags.txt
  src/main/ruby/truffleruby/core/regexp.rb
  test/mri/excludes/TestRegexp.rb
Labels: in-ci, shopify, OCA Verified

#3409 [Compatibility] Implement Time#deconstruct_keys
  CHANGELOG.md
  spec/ruby/core/time/deconstruct_keys_spec.rb
  spec/tags/core/time/deconstruct_keys_tags.txt
  src/main/ruby/truffleruby/core/time.rb
  test/mri/excludes/TestTime.rb
Labels: in-ci, shopify, OCA Verified

#3415 Handle positional or keywords args for Struct without keyword_init: true
  CHANGELOG.md
  spec/tags/core/struct/initialize_tags.txt
  spec/tags/core/struct/new_tags.txt
  src/main/ruby/truffleruby/core/struct.rb
Labels: in-ci, shopify, OCA Verified
