Repository oracle/truffleruby, pull requests merged in 2025-05, with the labels that each got.

#3817 Add mise instructions on ruby-managers.md
  doc/user/ruby-managers.md
Labels: documentation, in-ci, OCA Verified

#3872 Implement Integer.sqrt for large integers
  spec/tags/core/integer/sqrt_tags.txt
  src/main/ruby/truffleruby/core/integer.rb
Labels: in-ci, OCA Verified

#3861 Fix cext support for google-protobuf
  .github/workflows/ci.yml
  CHANGELOG.md
  lib/cext/include/truffleruby/truffleruby-abi-version.h
  lib/truffle/truffle/cext.rb
  spec/ruby/core/exception/frozen_error_spec.rb
  spec/ruby/language/def_spec.rb
  spec/ruby/optional/capi/exception_spec.rb
  spec/ruby/optional/capi/ext/exception_spec.c
  spec/ruby/optional/capi/ext/object_spec.c
  spec/ruby/optional/capi/object_spec.rb
  spec/tags/language/def_tags.txt
  src/main/c/cext/exception.c
  src/main/java/org/truffleruby/core/exception/CoreExceptions.java
  src/main/java/org/truffleruby/core/module/ModuleFields.java
  src/main/java/org/truffleruby/core/support/TypeNodes.java
  tool/generate-cext-trampoline.rb
Labels: cexts, compatibility, in-ci, shopify, OCA Verified
